Exams: migrate exam java files to kotlin (fixes #3116)
open-learning-exchange/myplanet pull request #3135
Opened 2024-02-18 09:58 UTC by BryanGazali

converted java files in exam folder to kotlin

2024-02-19 11:49 UTC, Okuro3499 commented
@BryanGazali can you do a rebase with master to resolve some errors on `BaseExamFragment`

2024-02-19 11:49 UTC, Okuro3499 requested changes
@BryanGazali can you do a rebase with master to resolve some errors on BaseExamFragment

2024-02-20 09:39 UTC, Okuro3499 approved these changes

2024-02-21 20:01 UTC, dogi approved these changes

2024-02-21 20:03 UTC, merged