my courses: text changes based on selections (fixes  #3569)
open-learning-exchange/myplanet pull request #3571
Opened 2024-06-06 16:05 UTC by strawberrybread

fixes #3569

[issue #3569.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/8303abae-6025-4d95-a2f3-bf0bdb8a639c)

Needs translations for the new string.

2024-06-06 16:16 UTC, rlam20 approved these changes

2024-06-06 16:30 UTC, ewhang5 approved these changes

2024-06-06 18:03 UTC, Okuro3499 requested changes
For the translations use google translate or chatgpt

2024-06-07 09:40 UTC, Okuro3499 approved these changes

2024-06-07 17:11 UTC, dogi approved these changes

2024-06-07 17:21 UTC, merged