view member details in teams/enterprise (fixes #3546)
open-learning-exchange/myplanet pull request #3614
Opened 2024-06-13 19:37 UTC by rlam20

fixes #3546 
Matches info stored in planet 
![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/fc0570ea-1299-44f7-a086-e8d7a354d30c)

2024-06-14 14:25 UTC, ewhang5 requested changes
seems like the profile pages show a white box rather than the profile picture that they have set.

2024-06-14 14:31 UTC, strawberrybread commented
is there a way for users to hide their personal info like DOB, email, phone number?

2024-06-14 14:39 UTC, Okuro3499 commented
@strawberrybread no they can't hide

2024-06-14 14:43 UTC, Okuro3499 requested changes
@rlam20 works great and would be better if you show the profile images

2024-06-14 14:43 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamMember/AdapterJoinedMember.kt
> -            .load(list[position].userImage)
this is the line that show the image. why is it removed? is it replaced by something else?

2024-06-14 19:34 UTC, Okuro3499 commented
![Screenshot_20240614_223350](https://github.com/open-learning-exchange/myplanet/assets/64019708/048471c5-e786-4563-9fac-c714a0a3065f)

2024-06-14 19:34 UTC, Okuro3499 approved these changes

2024-06-14 19:39 UTC, ewhang5 commented
i think this could look even better if the profile pictures are in the shape of a circle, but maybe that is for a future issue. looks great right now too

2024-06-14 19:39 UTC, ewhang5 approved these changes

2024-06-17 12:14 UTC, strawberrybread approved these changes

2024-06-17 19:12 UTC, dogi approved these changes

2024-06-17 19:15 UTC, merged