actions: less warnings is more (fixes #3654)
open-learning-exchange/myplanet pull request #3655
Opened 2024-06-19 14:52 UTC by strawberrybread

fixes #3654

2024-06-20 16:19 UTC, Okuro3499 approved these changes

2024-06-20 16:26 UTC, rlam20 approved these changes

2024-06-20 19:01 UTC, ewhang5 approved these changes

2024-06-21 17:22 UTC, dogi approved these changes

2024-06-21 17:29 UTC, dogi requested changes

2024-06-21 17:29 UTC, dogi commented on app/src/main/AndroidManifest.xml
> +    </queries>
needs to get also into the `AndroidManifest.lite`

2024-06-24 18:58 UTC, dogi approved these changes

2024-06-24 19:00 UTC, merged