syncactivity: team selection (fixes #3668)
open-learning-exchange/myplanet pull request #3677
Opened 2024-06-21 14:28 UTC by strawberrybread

fixes #3668 

[issue #3668.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/78e76e16-909b-44fa-a19a-87eab25a1b44)

2024-06-21 16:26 UTC, Okuro3499 commented
first time selecting a team I get this crash
```
FATAL EXCEPTION: main
Process: org.ole.planet.myplanet, PID: 22356
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
	at io.realm.BaseRealm.checkIfValid(BaseRealm.java:525)
	at io.realm.OrderedRealmCollectionImpl.get(OrderedRealmCollectionImpl.java:137)
	at io.realm.RealmResults.get(RealmResults.java:71)
	at org.ole.planet.myplanet.ui.sync.SyncActivity$showConfigurationUIElements$2.onItemSelected(SyncActivity.kt:615)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
	at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

2024-06-21 16:36 UTC, Okuro3499 requested changes

2024-06-21 16:36 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
>          } else if (serverConfigAction == "save") {
the functionality works here when you click the save button. you need to migrate this functionality to the itemSelect click

2024-06-24 17:42 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/sync/SyncActivity.kt
> +                                }
only these 3 lines are necessary for this functionality.
I have noticed only these buttons have the functionality to dismiss the dialog
```
.positiveText
.negativeText
.neutralText
.onPositive
.onNeutral
```
so we need to figure a way of passing the dialog to this click listener to be able to dismiss

2024-06-25 16:30 UTC, Okuro3499 approved these changes

2024-06-25 16:49 UTC, rlam20 approved these changes

2024-06-25 16:56 UTC, ewhang5 approved these changes

2024-06-26 14:48 UTC, merged