update notifyDataSetChanged implementations (fixes #3747)
open-learning-exchange/myplanet pull request #3748
Opened 2024-07-01 17:10 UTC by rlam20

fixes #3747

2024-07-01 18:29 UTC, Okuro3499 requested changes
we get a crash when you click one of the chats from the history list then when still viewing click another chat

```
FATAL EXCEPTION: main
Process: org.ole.planet.myplanet, PID: 3859
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionQueryViewHolder{fcbe0f5 position=2 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{75bd073 VFED..... ......I. 0,62-966,647 #7f0a0468 app:id/recycler_gchat}, adapter:org.ole.planet.myplanet.ui.chat.ChatAdapter@fc65798, layout:androidx.recyclerview.widget.LinearLayoutManager@78cfb30, context:org.ole.planet.myplanet.ui.dashboard.DashboardActivity@8b96ff1
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6590)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6796)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4591)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4346)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.slidingpanelayout.widget.SlidingPaneLayout.onLayout(SlidingPaneLayout.java:874)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23694)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)

```

2024-07-01 18:36 UTC, ewhang5 requested changes
Had the same issue but on the phone emulator. (takes a few seconds to see the error box come up in the video)

https://github.com/open-learning-exchange/myplanet/assets/59347000/925dc9a8-dfe1-48e6-8fb0-a7a61c61de78

2024-07-02 12:54 UTC, strawberrybread commented
Changes looks good, just need to address conflicts.

2024-07-02 15:38 UTC, strawberrybread approved these changes

2024-07-02 18:02 UTC, ewhang5 approved these changes

2024-07-03 15:07 UTC, dogi approved these changes

2024-07-03 16:27 UTC, ewhang5 commented on app/src/main/res/values-ne/strings.xml
> +    <string name="no_teams">टोलीहरू उपलब्ध छैनन्</string>
this is causing builds to fail and for some reason is in the master branch, so i think this change should be pushed to master asap

2024-07-03 16:29 UTC, ewhang5 approved these changes

2024-07-03 17:20 UTC, merged