chat: smoother refresh on submit (fixes #3784)
open-learning-exchange/myplanet pull request #3786
Opened 2024-07-05 14:07 UTC by Okuro3499

fixes #3784

2024-07-05 14:38 UTC, strawberrybread approved these changes

2024-07-05 14:50 UTC, rlam20 requested changes
looks good, but when you start with an empty chat list and start a new chat, the list does not refresh: 
![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/4115fae3-040d-4150-bb65-97b6e9842e33)


However once you hit the 'new chat' button it will all show up

2024-07-08 10:15 UTC, Okuro3499 commented
@rlam20 test for updates

2024-07-08 14:57 UTC, rlam20 approved these changes

2024-07-08 15:00 UTC, ewhang5 approved these changes

2024-07-08 15:29 UTC, strawberrybread approved these changes

2024-07-08 19:20 UTC, dogi approved these changes

2024-07-08 19:22 UTC, merged