course steps: goes to last visited step (fixes #3800)
open-learning-exchange/myplanet pull request #3801
Opened 2024-07-09 13:31 UTC by strawberrybread

fixes #3800 

[issue #3800.webm](https://github.com/open-learning-exchange/myplanet/assets/112584985/384d223e-75ca-494d-a3e1-203af36ac747)

2024-07-09 16:57 UTC, Okuro3499 requested changes
@strawberrybread still does not go to the last visited step 
[Screen_recording_20240709_195303.webm](https://github.com/open-learning-exchange/myplanet/assets/64019708/0efd17b0-2f55-43fe-9c0d-aea6ae3e2e17)

2024-07-10 14:31 UTC, ewhang5 approved these changes

2024-07-15 14:26 UTC, Okuro3499 requested changes
after going throught the last step and clicking finish maybe we could reset to have it start on the first step
[Uploading Screen_recording_20240715_172143.webm…]()

2024-07-16 18:08 UTC, Okuro3499 approved these changes

2024-07-16 18:09 UTC, Okuro3499 commented
@strawberrybread resolve the conflicts

2024-07-16 19:06 UTC, rlam20 approved these changes

2024-07-16 19:18 UTC, dogi approved these changes

2024-07-17 17:51 UTC, dogi approved these changes

2024-07-17 17:53 UTC, merged