resolve build warning (fixes #3793)
open-learning-exchange/myplanet pull request #3805
Opened 2024-07-09 16:47 UTC by rlam20

![image](https://github.com/open-learning-exchange/myplanet/assets/52076121/9b00d27f-70d0-40cf-b574-e1f6a96120b4)

2024-07-09 17:04 UTC, Okuro3499 requested changes

2024-07-09 17:04 UTC, Okuro3499 commented on app/src/main/res/values/strings.xml
> +    <string name="visit_count" translatable="false">%s (%d %s)</string>
adding `translatable="false"` means there is a language that the string is not translated in. in this case it is the somali language

2024-07-09 17:04 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/model/RealmNotification.kt
> +}
I don't think this should be in this branch

2024-07-09 17:24 UTC, Okuro3499 commented
@rlam20 https://chatgpt.com/share/f8048c2c-08ab-41ad-8619-2803fd80b9df

2024-07-11 09:47 UTC, Okuro3499 approved these changes

2024-07-11 14:26 UTC, ewhang5 approved these changes

2024-07-11 15:41 UTC, strawberrybread approved these changes

2024-07-11 18:04 UTC, dogi approved these changes

2024-07-11 18:12 UTC, merged