myhealth: smoother texts (fixes #3847)
open-learning-exchange/myplanet pull request #3848
Opened 2024-07-12 16:47 UTC by ewhang5

fixes #3847

2024-07-15 13:19 UTC, strawberrybread requested changes
![image](https://github.com/user-attachments/assets/d85e97c6-1fb3-4788-a7c0-9f99572fe70d)

Formatting for `Name`  and `Contact` is showing up incorrectly

2024-07-15 14:08 UTC, Okuro3499 requested changes
agree with @strawberrybread comment this is how it should be
![Screenshot_20240715_163526](https://github.com/user-attachments/assets/fafc9678-f1cc-4a99-b758-b60394969b94)

2024-07-15 17:46 UTC, Okuro3499 approved these changes

2024-07-16 15:12 UTC, rlam20 approved these changes

2024-07-16 15:22 UTC, strawberrybread approved these changes

2024-07-16 18:26 UTC, dogi approved these changes

2024-07-16 18:29 UTC, dogi approved these changes

2024-07-16 18:30 UTC, merged