survey: close survey and return to list after completion (fixes #3833)
open-learning-exchange/myplanet pull request #3865
Opened 2024-07-16 15:49 UTC by strawberrybread

fixes #3833

[Screen_recording_20240716_114810.webm](https://github.com/user-attachments/assets/98a2e02c-42df-466a-a33c-6f7b8796c3db)

2024-07-16 17:55 UTC, Okuro3499 requested changes

2024-07-16 17:55 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/exam/BaseExamFragment.kt
> +//        }
we need this condition it checks if the survey is assigned to you

2024-07-17 15:59 UTC, ewhang5 approved these changes

2024-07-17 16:59 UTC, Okuro3499 approved these changes

2024-07-17 17:55 UTC, dogi approved these changes

2024-07-17 17:58 UTC, merged