sync: smoother texts (fixes #3864)
open-learning-exchange/myplanet pull request #3866
Opened 2024-07-16 15:49 UTC by ewhang5

fixes #3864

2024-07-16 16:51 UTC, Okuro3499 requested changes
check on versions in login and about activities
![Screenshot 2024-07-16 19 44 17 (1)](https://github.com/user-attachments/assets/2ca1b6b3-55e3-47ab-b323-3da31ad63db4)
![Screenshot 2024-07-16 19 46 31 (1)](https://github.com/user-attachments/assets/98989364-0e7c-4de4-97e2-042f619e147d)

2024-07-16 18:55 UTC, rlam20 requested changes

2024-07-16 18:55 UTC, rlam20 commented on app/src/main/res/values-ar/strings.xml
> +    <string name="last_sync">آخر مزامنة مع الخادم: %s</string>
آخر مزامنة مع الخادم: s%

2024-07-16 18:55 UTC, rlam20 commented on app/src/main/res/values-ar/strings.xml
> +    <string name="version">الإصدار %s</string>
الإصدار s%

2024-07-16 18:55 UTC, rlam20 commented on app/src/main/res/values-ar/strings.xml
> +    <string name="last_sync_date">تاريخ آخر مزامنة: %s</string>
تاريخ آخر مزامنة: s%

2024-07-16 19:06 UTC, rlam20 approved these changes

2024-07-16 19:07 UTC, rlam20 approved these changes

2024-07-17 15:09 UTC, strawberrybread approved these changes

2024-07-17 16:09 UTC, Okuro3499 approved these changes

2024-07-17 17:57 UTC, dogi approved these changes

2024-07-17 18:06 UTC, merged