3888 mycourses archive button if nothing selected
open-learning-exchange/myplanet pull request #3905
Opened 2024-07-18 20:53 UTC by rlam20

![image](https://github.com/user-attachments/assets/b84ea2b6-b351-4f89-afe4-f0e63f0895e1)
![image](https://github.com/user-attachments/assets/b3c7d618-7729-4113-b85e-c64487029bc0)
![image](https://github.com/user-attachments/assets/12aff542-aab4-4737-bd6d-28dbb95b0d01)

can extend this later to give the archive button functionality

2024-07-19 09:53 UTC, Okuro3499 approved these changes

2024-07-19 14:15 UTC, strawberrybread approved these changes

2024-07-19 19:35 UTC, ewhang5 approved these changes

2024-07-22 15:45 UTC, dogi requested changes

2024-07-22 15:45 UTC, dogi commented on app/src/main/res/values/strings.xml
> +    <string name="are_you_sure_you_want_to_archive_this_course">Are you sure you want to archive this course?</string>
this is at lines 628/629 but should be like the others 1081/1082

2024-07-22 15:45 UTC, dogi commented on app/src/main/res/values/strings.xml
> +    <string name="are_you_sure_you_want_to_archive_this_course">Are you sure you want to archive this course?</string>
... or we move all the other strings in the other string files to line 628

2024-07-22 16:58 UTC, dogi approved these changes

2024-07-22 17:54 UTC, merged