settings: toolbar showing after language change (fixes #3935)
open-learning-exchange/myplanet pull request #3952
Opened 2024-07-26 14:36 UTC by strawberrybread

fixes #3935 

[Screen_recording_20240726_103333.webm](https://github.com/user-attachments/assets/75deb1f8-5d46-4c11-bfa9-b7e540791558)

2024-07-26 15:29 UTC, ewhang5 approved these changes

2024-07-26 16:00 UTC, rlam20 approved these changes

2024-07-26 17:05 UTC, ewhang5 requested changes
This actually ends up changing the dark mode. Do you think you could instead try to see if there is a way to solve this without changing the dark mode aspect of it? The solution would most likely be trying to see if you can find a way to not use PreferencesTheme or if you could modify PreferencesTheme to fix this issue?

2024-07-29 13:49 UTC, Okuro3499 commented
> This actually ends up changing the dark mode. Do you think you could instead try to see if there is a way to solve this without changing the dark mode aspect of it? The solution would most likely be trying to see if you can find a way to not use PreferencesTheme or if you could modify PreferencesTheme to fix this issue?

@ewhang5 how does it affect the dark theme? not experiencing any issues

https://github.com/user-attachments/assets/2f662077-6e5c-4a64-a929-51f5b02b81bd

2024-07-29 14:49 UTC, ewhang5 commented
> > This actually ends up changing the dark mode. Do you think you could instead try to see if there is a way to solve this without changing the dark mode aspect of it? The solution would most likely be trying to see if you can find a way to not use PreferencesTheme or if you could modify PreferencesTheme to fix this issue?
> 
> @ewhang5 how does it affect the dark theme? not experiencing any issues
> 
>  Screen_recording_20240729_164022.mp4

The dark mode is originally supposed to look like this for the setting page:
<img width="272" alt="Screenshot 2024-07-29 at 9 48 15 AM" src="https://github.com/user-attachments/assets/d757d657-5ff5-49f0-8d98-007a3d9069f9">

2024-07-30 17:03 UTC, ewhang5 approved these changes

2024-07-30 18:57 UTC, Okuro3499 approved these changes

2024-07-30 20:40 UTC, dogi approved these changes

2024-07-30 20:43 UTC, merged