sync: configuration
open-learning-exchange/myplanet pull request #3966
Opened 2024-07-30 14:35 UTC by Okuro3499

[Screen_recording_20240730_173107.webm](https://github.com/user-attachments/assets/5392b3f4-37be-43e6-8b27-76d32a2d5778)

2024-07-30 15:52 UTC, strawberrybread approved these changes

2024-07-30 15:54 UTC, ewhang5 approved these changes

2024-07-30 15:56 UTC, ewhang5 commented
I think this draft is closer to what dogi wanted. The only things he told me were to get rid of clear data button, and remove sync button so that it becomes automatic. I think spacing could be touched on a little bit, and then I also added text above the toggle group saying "Sync to server" just as a little explanation which I think could be helpful. @Okuro3499 what do you think the next steps should be for this pr?

2024-07-30 16:06 UTC, ewhang5 requested changes
I think we are getting a lot closer, but I think the aim as of now is to address what I mentioned above. It seems like this may be branched off of my branch, so let me know if you want me to help out and help address any of the issues mentioned!

2024-08-01 11:52 UTC, dogi commented
#3982

2024-08-01 11:52 UTC, closed without merging