sync: more server configurations (fixes #4031)
open-learning-exchange/myplanet pull request #4032
Opened 2024-08-05 17:04 UTC by Okuro3499

fixes #4031

2024-08-05 17:51 UTC, rlam20 requested changes
small issue 
![image](https://github.com/user-attachments/assets/cbb17e8b-9c98-4242-97b7-0043a9894222)
when you switch from manual back to automatic it will change the text to 'more' even if the list is expanded 

otherwise looks good and works great

2024-08-05 18:31 UTC, Okuro3499 commented
> small issue ![image](https://private-user-images.githubusercontent.com/52076121/355195805-cbb17e8b-9c98-4242-97b7-0043a9894222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODA2OTMsIm5iZiI6MTcyMjg4MDM5MywicGF0aCI6Ii81MjA3NjEyMS8zNTUxOTU4MDUtY2JiMTdlOGItOWM5OC00MjQyLTk3YjctMDA0M2E5ODk0MjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE3NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMzAzMmY0YzRlZWJkZjcwMDAzYzdiNTg2OWQwODk0NjFiMTU2N2UyYzI2YTk2YmE2YWEwZWZjMmZkZjllNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.16mZTZj3RtHmfknwsMFQez3TCgaBhH-yXb8KewYuM-8) when you switch from manual back to automatic it will change the text to 'more' even if the list is expanded
> 
> otherwise looks good and works great

@rlam20 issue fixed test again

2024-08-05 18:40 UTC, AdhamElAsfar99 approved these changes

2024-08-06 15:07 UTC, rlam20 approved these changes

2024-08-06 15:19 UTC, strawberrybread approved these changes

2024-08-06 15:33 UTC, ewhang5 approved these changes

2024-08-06 20:29 UTC, dogi approved these changes

2024-08-06 20:30 UTC, merged