dark mode: make icons and text visible (fixes #4025)
open-learning-exchange/myplanet pull request #4100
Opened 2024-08-08 19:19 UTC by AdhamElAsfar99

fixes #4025

![my_library](https://github.com/user-attachments/assets/6274ddd9-810f-48af-b46a-46fdc0a306e1)

![my_courses](https://github.com/user-attachments/assets/c35a5529-f033-427e-b537-fc0b3d8b4d72)

![Library](https://github.com/user-attachments/assets/c5fdcf72-e633-49d2-8873-ecd9da0d7837)

![Courses](https://github.com/user-attachments/assets/f352a405-305b-46c0-834d-43aab1ae13c7)

2024-08-09 10:58 UTC, Okuro3499 requested changes
could the color if the description match that of the title (white) still not easy to see also do the same for library
![my_courses](https://github.com/user-attachments/assets/c35a5529-f033-427e-b537-fc0b3d8b4d72)

2024-08-09 17:56 UTC, Okuro3499 approved these changes

2024-08-12 12:19 UTC, strawberrybread approved these changes

2024-08-12 15:21 UTC, rlam20 approved these changes

2024-08-12 18:16 UTC, dogi approved these changes

2024-08-12 18:19 UTC, merged