darkmode: add select team to the login page
open-learning-exchange/myplanet pull request #4143
Opened 2024-08-13 17:13 UTC by AdhamElAsfar99

fixes #4126 

![image](https://github.com/user-attachments/assets/58087223-8c6e-478d-968b-7d3acdb6464b)

2024-08-13 17:47 UTC, Okuro3499 requested changes
@AdhamElAsfar99 we have 5 login layouts only 2 are updated to have the team. Update the other 3

<img width="347" alt="Screenshot 2024-08-13 at 20 45 53" src="https://github.com/user-attachments/assets/19691600-8de1-4a91-ad06-993b084d0fd4">

2024-08-14 14:10 UTC, strawberrybread approved these changes

2024-08-14 14:18 UTC, Okuro3499 approved these changes

2024-08-14 15:16 UTC, rlam20 requested changes
![image](https://github.com/user-attachments/assets/97efb5f4-dcd2-4b75-be1d-c208f0065c73)
Maybe make the arrow to open the dropdown menu white to make it more visible. Other than that works great.

2024-08-14 19:10 UTC, dogi approved these changes

2024-08-14 19:12 UTC, merged