reports: smoother translate strings (fixes #4301)
open-learning-exchange/myplanet pull request #4358
Opened 2024-09-06 18:53 UTC by Kuljeet1998

Fixes #4301 

![image](https://github.com/user-attachments/assets/fd13d640-466e-46b1-bb29-84e081d9e9ff)
![image](https://github.com/user-attachments/assets/f65a5278-055b-4ae5-a2e8-85add3f788f1)
![image](https://github.com/user-attachments/assets/4c23849c-ed95-463d-8e20-5bbfde0c9e6c)
![image](https://github.com/user-attachments/assets/519c3bd3-8960-49a3-912c-254a4a119e42)

2024-09-06 19:12 UTC, deeppp15 approved these changes

2024-09-06 19:51 UTC, AdhamElAsfar99 approved these changes

2024-09-09 18:07 UTC, Okuro3499 requested changes
the title `add report` is not translated

2024-09-09 18:52 UTC, dogi approved these changes

2024-09-09 19:13 UTC, Okuro3499 approved these changes

2024-09-11 17:40 UTC, merged