myachievements: smoother achievements ( fixes #4350)
open-learning-exchange/myplanet pull request #4370
Opened 2024-09-09 20:57 UTC by deeppp15

### Description
fixes #4350
Just Changed achievements, other changes coming soon...

![WhatsApp Image 2024-09-09 at 16 55 30_a25da653](https://github.com/user-attachments/assets/af6139e2-b603-4e29-afc7-5fba4e1eeaa2)

![WhatsApp Image 2024-09-09 at 16 55 29_547e8bb7](https://github.com/user-attachments/assets/ec547611-0dba-4f41-962f-35c966874c14)

2024-09-10 18:39 UTC, Okuro3499 requested changes

2024-09-10 18:39 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
> +                rowAchievementBinding.tvTitle.setTextColor(textColor)
I think this would be better if done in the xml file

2024-09-11 17:09 UTC, deeppp15 commented on app/src/main/java/org/ole/planet/myplanet/ui/userprofile/AchievementFragment.kt
> +                rowAchievementBinding.tvTitle.setTextColor(textColor)
Hi @Okuro3499 , implemented in XML please review it.

2024-09-11 17:48 UTC, Okuro3499 approved these changes

2024-09-11 18:37 UTC, dogi approved these changes

2024-09-11 18:42 UTC, Kuljeet1998 approved these changes

2024-09-11 18:48 UTC, merged