notification: smoother darkmode elements
open-learning-exchange/myplanet pull request #4432
Opened 2024-09-18 20:28 UTC by deeppp15

## Description

- Removed two files which were from previous notification changes
- We had duplicate row notifications and notification fragment.

## Code Changes
- Removed the old files 
- Used exisiting spineer item instead of default android.

## Screenshot

![image](https://github.com/user-attachments/assets/36e6c12c-850c-448d-ba73-e5831324b919)

2024-09-19 12:03 UTC, Okuro3499 requested changes
all filter is not visible
![Screenshot_20240919_145843](https://github.com/user-attachments/assets/5f2926ab-6fac-4231-9bab-d9572c948c4a)

2024-09-19 15:47 UTC, deeppp15 commented
> all filter is not visible ![Screenshot_20240919_145843](https://private-user-images.githubusercontent.com/64019708/368978640-5f2926ab-6fac-4231-9bab-d9572c948c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjA1MjksIm5iZiI6MTcyNjc2MDIyOSwicGF0aCI6Ii82NDAxOTcwOC8zNjg5Nzg2NDAtNWYyOTI2YWItNmZhYy00MjMxLTliYWItZDk1NzJjOTQ4YzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE1MzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMWIyN2ZkMWEzMWEyNGYyZjMzNDMwMjJhMGM2ZjMxNjkwZGMzOGI0NWVhY2E3ZTI5MGNhYzZiNDVjMjhmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.72lR8DmGhbpTrN5iLHjUjePZwzvFyicOt5AyYG7FXlc)

Hi @Okuro3499 ,

Could you try invalidating cache and reviewing again. I dont see it on my end.

https://github.com/user-attachments/assets/ea3cabb6-236d-4fd3-bd1d-6155358f0077

2024-09-19 18:34 UTC, dogi commented on app/src/main/res/layout/fragment_notification.xml
> +
oops

2024-09-19 19:19 UTC, Okuro3499 commented
> > all filter is not visible ![Screenshot_20240919_145843](https://private-user-images.githubusercontent.com/64019708/368978640-5f2926ab-6fac-4231-9bab-d9572c948c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjA1MjksIm5iZiI6MTcyNjc2MDIyOSwicGF0aCI6Ii82NDAxOTcwOC8zNjg5Nzg2NDAtNWYyOTI2YWItNmZhYy00MjMxLTliYWItZDk1NzJjOTQ4YzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE1MzcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMWIyN2ZkMWEzMWEyNGYyZjMzNDMwMjJhMGM2ZjMxNjkwZGMzOGI0NWVhY2E3ZTI5MGNhYzZiNDVjMjhmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.72lR8DmGhbpTrN5iLHjUjePZwzvFyicOt5AyYG7FXlc)
> 
> Hi @Okuro3499 ,
> 
> Could you try invalidating cache and reviewing again. I dont see it on my end. @Kuljeet1998 are you also seeing the same UI as Gideon ?
> 
>  Notification.changes.mp4

@deeppp15 I still have the issue
[nit.webm](https://github.com/user-attachments/assets/e7bb3e90-88d5-4213-84e8-530788e0f820)

2024-09-19 19:51 UTC, Kuljeet1998 commented
@deeppp15 Yes, I don't see that either.
![image](https://github.com/user-attachments/assets/7319a09f-b411-403a-963a-046854ab3acd)

2024-09-20 19:03 UTC, deeppp15 commented
Hi @Okuro3499  @Kuljeet1998 

I have tried my changes on multiple devices they are working fine here is an image from another emulator 
![image](https://github.com/user-attachments/assets/6f15185f-3859-4ff0-a7ba-f306b854650d)
.

- Make sure you are pulling changes after checking out.

2024-09-23 10:52 UTC, Okuro3499 requested changes
@deeppp15 I can now see the filter. make the dropdown button visible in darkmode

2024-09-24 14:24 UTC, Okuro3499 approved these changes
![Screenshot_20240924_171502](https://github.com/user-attachments/assets/baed0131-d3b5-434b-9725-3e33681f006a)

2024-09-24 18:03 UTC, Kuljeet1998 approved these changes

2024-09-24 18:40 UTC, dogi approved these changes

2024-09-24 18:43 UTC, merged