mylife: smoother myachievements strings (fixes #4504)
open-learning-exchange/myplanet pull request #4505
Opened 2024-09-27 18:28 UTC by Kuljeet1998

![image](https://github.com/user-attachments/assets/70b0c6c2-9b73-4da0-a35c-fa780fbe7fa0)

2024-09-27 18:56 UTC, deeppp15 approved these changes

2024-09-30 09:57 UTC, Okuro3499 requested changes
extract this to the string files and translate

2024-10-01 17:35 UTC, Okuro3499 approved these changes

2024-10-01 18:02 UTC, dogi approved these changes

2024-10-01 18:03 UTC, deeppp15 approved these changes

2024-10-01 18:05 UTC, merged