all: smoother download (fixes #3955)
open-learning-exchange/myplanet pull request #4550
Opened 2024-10-04 17:42 UTC by Kuljeet1998

Fix: #3955 

Case 1: more than 1 file to download - disable `Finish` button

https://github.com/user-attachments/assets/921ad77c-1eb0-4afa-8a62-9f1060866a1e

Case 2: only 1 file to download - `Finish` button visible 

https://github.com/user-attachments/assets/61d6b7dc-dcc2-4c6c-80bd-a32f1080fb25

2024-10-07 10:44 UTC, Okuro3499 requested changes
is this complete? the finish button should not be visible for all downloads and I also think it will be better if the `stop download button` is hidden once the download is complete

2024-10-07 16:18 UTC, Kuljeet1998 commented
Case 1: multiple download 


https://github.com/user-attachments/assets/2e100fb2-980a-4bf7-924d-76814ec3c5cf

Case 2: one download 


https://github.com/user-attachments/assets/3cf1346c-38f6-4c44-bb12-c0c6056d0eac

2024-10-08 12:00 UTC, Okuro3499 approved these changes

2024-10-08 19:11 UTC, dogi approved these changes

2024-10-08 19:13 UTC, merged