login: smoother teams list on small screens (fixes #4571)
open-learning-exchange/myplanet pull request #4624
Opened 2024-10-11 20:15 UTC by deeppp15

## Description

- fixes #4571 
- added constraintVerticalBias

## Screenshot

![image](https://github.com/user-attachments/assets/cfd2527d-e824-4469-bc17-48b247f2e352)

2024-10-14 10:49 UTC, Okuro3499 requested changes
tested in emulator `small phone api 30`
![Screenshot_20241014_134753](https://github.com/user-attachments/assets/2a2af2e0-3bbf-4bcb-ab9f-89d379fd008e)

2024-10-14 20:30 UTC, deeppp15 commented
## Screenshots of updated code

### API 30 small phone 

  ![login overlap api 30 small phone](https://github.com/user-attachments/assets/831c95b3-1c7c-40eb-b68b-c00117ee6483)


### API 30 Larger phone
  ![image](https://github.com/user-attachments/assets/dbc64828-6a9f-4c88-b0fb-8eeaab704d75)

2024-10-15 13:20 UTC, Okuro3499 approved these changes

2024-10-15 19:04 UTC, dogi approved these changes

2024-10-15 19:05 UTC, merged