all: smoother sidebar (fixes #4596)
open-learning-exchange/myplanet pull request #4626
Opened 2024-10-14 18:55 UTC by Kuljeet1998

Fixes: #4596 

![image](https://github.com/user-attachments/assets/c4f57faf-93e1-4d04-a21f-fb62db70c037)

![image](https://github.com/user-attachments/assets/694a0007-9fe1-4bf7-b196-c7b9ad535769)

2024-10-14 19:25 UTC, deeppp15 approved these changes

2024-10-14 19:37 UTC, Okuro3499 requested changes
I don't think issue is fixed
[Screen_recording_20241014_220952.webm](https://github.com/user-attachments/assets/8cd44e80-c885-45c8-83ed-17b8f5c8ca1f)

2024-10-14 19:43 UTC, deeppp15 commented
On my end it seems fixed

## Screenshot
![image](https://github.com/user-attachments/assets/925c029b-c003-48b2-af2e-3a4943014d2d)

2024-10-15 13:33 UTC, Okuro3499 commented
It’s responsive for some devices, some not
<img width="1512" alt="Screenshot 2024-10-15 at 16 30 46" src="https://github.com/user-attachments/assets/ff8559bb-5c15-4a1b-8135-c8dc8a9108df">

2024-10-15 19:25 UTC, Okuro3499 approved these changes

2024-10-15 19:47 UTC, dogi approved these changes

2024-10-15 19:48 UTC, merged