teams: smoother tasks assigning (fixes #4787)
open-learning-exchange/myplanet pull request #4798
Opened 2024-11-21 20:36 UTC by deeppp15

## Description

- fixes #4787
- Added checks if the team has no members

## Testing 
- create new teams and assign tasks.

## Screenshots
[No team members to assign task.webm](https://github.com/user-attachments/assets/f492febc-cd85-4824-9e74-62868cf7fcde)

2024-11-22 12:32 UTC, Okuro3499 requested changes

2024-11-22 12:32 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
> +            Toast.makeText(context, "No Team members present to assign tasks", Toast.LENGTH_SHORT).show()
translate these strings

2024-11-22 12:32 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
> +                    Toast.makeText(context, "No member selected. Please try again.", Toast.LENGTH_SHORT).show()
this one too

2024-11-22 19:22 UTC, deeppp15 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamTask/TeamTaskFragment.kt
> +            Toast.makeText(context, "No Team members present to assign tasks", Toast.LENGTH_SHORT).show()
Updated translations please check @Okuro3499

2024-11-22 20:16 UTC, Okuro3499 approved these changes

2024-11-25 18:19 UTC, Kuljeet1998 approved these changes

2024-11-25 19:28 UTC, dogi approved these changes

2024-11-25 19:30 UTC, merged