teams: smoother team removal (fixes #4819)
open-learning-exchange/myplanet pull request #4829
Opened 2024-12-02 22:37 UTC by deeppp15

## Description

- fixes #4819

## Screenshot

https://github.com/user-attachments/assets/5d126f04-73d4-4c11-87ab-8eff07faad0b

2024-12-03 15:52 UTC, Okuro3499 requested changes
if you remove a team leader it is still not properly refreshed because if you exit the page and reopen you will see an accurate list
[Screen_recording_20241203_184929.webm](https://github.com/user-attachments/assets/8184d950-dca4-43ff-aa66-adee4b2b1498)

2024-12-03 21:31 UTC, deeppp15 commented
Hi @Okuro, I have fixed the make team leader, please check. Updated the binding configuration.
https://github.com/user-attachments/assets/84a95cf3-2686-4e6d-8c73-2cc24a870426

2024-12-04 11:10 UTC, Okuro3499 approved these changes

2024-12-04 16:46 UTC, Kuljeet1998 approved these changes

2024-12-04 19:32 UTC, dogi approved these changes

2024-12-04 19:51 UTC, merged