fixed top bar restriction for guests ( fixes #4863 )
open-learning-exchange/myplanet pull request #4869
Opened 2024-12-12 14:17 UTC by Avinash-Codes

fixes #4863 

https://github.com/user-attachments/assets/6f62e26a-490b-439e-867d-9872a148a2ff

2024-12-12 16:51 UTC, dogi requested changes

2024-12-12 16:51 UTC, dogi commented on app/src/main/res/values/strings.xml
> +    <string name="typename">Type</string>
there are 5 more strings.xml

2024-12-12 16:51 UTC, dogi commented on app/src/main/res/layout/fragment_team.xml
> +                android:text="@string/typename"
@Avinash-Codes not sure if this solves the issue
in other words think this and following change are not necessary

2024-12-13 10:30 UTC, Okuro3499 requested changes

2024-12-13 10:30 UTC, Okuro3499 commented on app/src/main/res/layout/fragment_team.xml
> +                android:text="@string/typename"
I also don't think string file changes are necessary for this pr. so revert these changes on the strings files

2024-12-13 19:49 UTC, dogi approved these changes

2024-12-13 19:52 UTC, Okuro3499 approved these changes

2024-12-13 19:52 UTC, deeppp15 approved these changes

2024-12-13 19:59 UTC, merged