app: smoother theme logic on orientation changes (fixes #4859)
open-learning-exchange/myplanet pull request #4871
Opened 2024-12-12 21:56 UTC by deeppp15

## Description

- fixes #4859

## Video

[changing orientation with darkmode.webm](https://github.com/user-attachments/assets/3115f298-0a84-4af1-909c-d438642ad2cb)

2024-12-13 11:08 UTC, Okuro3499 requested changes
if the device theme is set to light mode and the device dark theme is set to "follow system" rotating after setting the to dark theme rotating the screen does not remember the user choice and resets back to follow system
[Screen_recording_20241213_133304.webm](https://github.com/user-attachments/assets/12920c09-e6c5-44ff-9630-9dc4327b6e16)

2024-12-17 20:30 UTC, deeppp15 commented
Hi @Okuro3499 checkout the below tests for this PR

- System : Dark 

https://github.com/user-attachments/assets/83aba7c1-d185-4201-bd17-3eef2bdcd4a0

- System : Light

https://github.com/user-attachments/assets/36a082cc-ebcf-4d04-beaa-d8db3c7b76e4

2024-12-18 14:11 UTC, Okuro3499 approved these changes

2024-12-18 14:29 UTC, Avinash-Codes approved these changes

2024-12-18 19:26 UTC, dogi approved these changes

2024-12-18 19:28 UTC, merged