theme: Smoother theme change (fixes #4879)
open-learning-exchange/myplanet pull request #4882
Opened 2024-12-16 15:29 UTC by Avinash-Codes

fixes #4879

2024-12-16 19:59 UTC, Okuro3499 requested changes

2024-12-16 19:59 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/MainApplication.kt
> -
revert this space change

2024-12-16 19:59 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
> +                )
you could revert this to be one line as before

2024-12-16 19:59 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/SettingActivity.kt
> +                        ArrayAdapter(
this too

2024-12-17 15:22 UTC, Okuro3499 requested changes

2024-12-17 15:22 UTC, Okuro3499 commented on app/src/main/res/values/strings.xml
> +    <string name="select">Select</string>
translate this in the other string files too

2024-12-17 15:56 UTC, Okuro3499 approved these changes

2024-12-17 17:13 UTC, deeppp15 approved these changes

2024-12-17 18:56 UTC, dogi requested changes

2024-12-17 18:56 UTC, dogi commented on app/src/main/res/values-fr/strings.xml
> +    <string name="select">Select</string>
system name is myPlanet

2024-12-17 19:01 UTC, dogi approved these changes

2024-12-17 19:04 UTC, merged