teams: smoother resource remove (fixes #491)
open-learning-exchange/myplanet pull request #4917
Opened 2024-12-23 22:52 UTC by deeppp15

## Description

- fixes #491
- Added removeResource function to remove the resourceId from teamsId object and reflect changes on UI.

## Screenshots

- When user is team leader 
[leader adding removing resources.webm](https://github.com/user-attachments/assets/b0b3f969-cf90-400c-b701-d3c03584d7db)

- When user is not team leader
![resourceNotLeader](https://github.com/user-attachments/assets/cdbf60db-9985-4dc2-89c4-978cd40b11f2)

2024-12-26 01:53 UTC, Kuljeet1998 approved these changes

2024-12-26 14:02 UTC, Avinash-Codes approved these changes

2025-01-05 21:25 UTC, Okuro3499 commented
@deeppp15 how does this work? was't able to figure it out

2025-01-05 21:27 UTC, Okuro3499 requested changes

2025-01-05 21:27 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
> +        val binding = RowTeamResourceBinding.inflate(LayoutInflater.from(context), parent, false)
why is these being renamed?

2025-01-05 21:27 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
> +        holder.binding.ivRemove.setOnClickListener {
these ones too from `rowTeamResourceBinding` to `holder.binding.`

2025-01-06 07:48 UTC, deeppp15 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
> +        holder.binding.ivRemove.setOnClickListener {
Hi @Okuro3499 , renamed variables

2025-01-06 07:49 UTC, deeppp15 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
> +        val binding = RowTeamResourceBinding.inflate(LayoutInflater.from(context), parent, false)
Hi @Okuro3499 , reverted variable names

2025-01-07 14:43 UTC, Okuro3499 commented
how does this work? I am a team leader of a team and I can't remove resources even for the teams I am not a team leader
[Screen_recording_20250107_171510.webm](https://github.com/user-attachments/assets/5cda7f97-1a42-446b-b3e9-7b1bad89ca5c)

2025-01-07 23:10 UTC, deeppp15 commented
Hi @Okuro3499 , added changes for better matching; also Team  "new test team" has invalid leader data. You may wanna test it with a different team.
[working with team leader.webm](https://github.com/user-attachments/assets/4e5122cb-1222-4ab2-9bbb-831bf2dd10f3)

2025-01-08 18:24 UTC, pavi38 approved these changes

2025-01-09 11:04 UTC, Okuro3499 requested changes
I created a new team as you suggested, and this fix only works when I add a resource and not sync. However, if I add a resource, sync it, then uninstall and reinstall the app to resync, the resource appears but cannot be deleted.

2025-01-09 18:02 UTC, deeppp15 commented
Hi @pavi38 and @Avinash-Codes could you please confirm if this issue is reproducible?

2025-01-13 11:08 UTC, Okuro3499 requested changes
the remove icon is only available when the resource is added on my planet and no sync is done

2025-03-06 11:57 UTC, Okuro3499 requested changes

2025-03-06 11:57 UTC, Okuro3499 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
> +import android.util.Log
@deeppp15 
1. remove logs
2. this works ok now just show the empty data placeholder if no data is left after removal
[Screen_recording_20250306_145402.webm](https://github.com/user-attachments/assets/758c873f-7310-4cb7-84a8-cb37ae14aadb)

2025-03-06 23:38 UTC, deeppp15 commented on app/src/main/java/org/ole/planet/myplanet/ui/team/teamResource/AdapterTeamResource.kt
> +import android.util.Log
Hi @Okuro3499 , resolved issues please check

2025-03-07 14:14 UTC, Okuro3499 approved these changes

2025-03-07 20:14 UTC, dogi approved these changes

2025-03-07 20:17 UTC, merged