mode:smoother mode switch (fixes #4931)
open-learning-exchange/myplanet pull request #4918
Opened 2024-12-26 15:35 UTC by Avinash-Codes

fixes #4931

2024-12-27 09:57 UTC, Okuro3499 requested changes
@Avinash-Codes the issue only required a background change for the layout that was in white to be fixed

2025-01-05 21:20 UTC, Okuro3499 approved these changes

2025-01-06 08:43 UTC, deeppp15 approved these changes

2025-01-06 19:13 UTC, dogi approved these changes

2025-01-06 19:19 UTC, merged