myCourses: smoother button styling (fixes #4925)
open-learning-exchange/myplanet pull request #4926
Opened 2024-12-30 21:18 UTC by deeppp15

## Description

- fixes #4925
- added styling changes

## Screenshot

[leave light mode.webm](https://github.com/user-attachments/assets/9390fc83-6084-4670-a504-ea1b80d7325b)
[leave button darkmode.webm](https://github.com/user-attachments/assets/b1300fce-b4b9-4e99-bd53-1a6ab5d48b4b)

2025-01-01 11:51 UTC, Avinash-Codes approved these changes

2025-01-02 12:49 UTC, Okuro3499 requested changes

2025-01-02 12:49 UTC, Okuro3499 commented on app/src/main/res/drawable/buttonblue.xml
> +            <gradient android:angle="-90" android:endColor="@color/colorPrimary" android:startColor="@color/colorPrimary" />
we try to maintain the app's blue theme in both dark and light mode. This change gives the button a black background in dark mode which is not what we want

2025-01-02 23:01 UTC, deeppp15 commented on app/src/main/res/drawable/buttonblue.xml
> +            <gradient android:angle="-90" android:endColor="@color/colorPrimary" android:startColor="@color/colorPrimary" />
![image](https://github.com/user-attachments/assets/947cbabe-d295-484e-91a0-04570c08007b)
So the changes are matching the lightmode, where the leave button follows the same theme as the section banner

2025-01-03 12:27 UTC, Okuro3499 commented on app/src/main/res/drawable/buttonblue.xml
> +            <gradient android:angle="-90" android:endColor="@color/colorPrimary" android:startColor="@color/colorPrimary" />
In darkmode the button should still be blue

2025-01-08 21:48 UTC, deeppp15 commented
## Button color reverted but align components persist

![image](https://github.com/user-attachments/assets/dea8626d-911b-462d-a353-381196057ef5)

2025-01-09 11:09 UTC, Okuro3499 requested changes
I don't see any difference between the screenshot in the issue https://github.com/open-learning-exchange/myplanet/issues/4925#issue-2763705910 and the courses page in this pr

2025-01-09 17:15 UTC, deeppp15 commented
Hi @Okuro3499 , the buttons are now aligned and of the same size
- existing(left) this PR(right)
![image](https://github.com/user-attachments/assets/f85ff43c-efe2-4827-8fc9-83edc359960d)

2025-01-14 12:40 UTC, Okuro3499 approved these changes

2025-01-14 18:30 UTC, dogi approved these changes

2025-01-14 18:32 UTC, merged